name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main   # runs whenever you push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # allow GitHub to mint an OIDC token
      contents: read     # allow checkout

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push image to GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/py-hello:$(date +%s)
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Azure Container Apps
        run: |
          RG_DEV=rg-proto-dev
          ENV_ID=$(az containerapp show -g "$RG_DEV" -n openvscode --query "properties.environmentId" -o tsv)
          az containerapp up \
            -g "$RG_DEV" \
            -n py-hello \
            --environment-id "$ENV_ID" \
            --ingress external \
            --target-port 8080 \
            --image $IMAGE
